### ISSUE TITLE
Setup appropriate license for modified template

### ISSUE THREAD

**Issue by lboxell** [gslab-econ/gslab_latex#1]
Ensure modified template meets the requirements outlined [here](https://github.com/gslab-econ/gslab_latex/blob/20b0482bcc8c38821c0565b096ae7aed6f3d7b5c/beamertheme_metropolis/orig/mtheme-master/README.md).

**Comment by arosenbe** [comment]
Task received. I'm finishing up the last trans task, but should get to this later today.

**Comment by arosenbe** [comment]
@lboxell can you please PR? This should just involve a read through the new [readme](https://github.com/gslab-econ/gslab_latex/blob/issue1-license/README.md) to check that it sounds good/looks alright and also meets the requirement you link to above.

**Comment by lboxell** [comment]
@arosenbe,

I think we want to be explicit that the modified template is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License and then note that this is because of the original template was licensed under the same license.

I also think we want a link in our readme under the license section to the original readme, as its not clear to me whether 'provide a link to the license' means the Creative Commons page or the readme page (and its easy to do both).

**Comment by arosenbe** [comment]
Thanks @lboxell. Can you let me know what you think about the [new readme](https://github.com/gslab-econ/gslab_latex/blob/a1cff9946bcee05efd6d99fc9ab78f4922eec314/README.md)?

**Comment by lboxell** [comment]
@arosenbe, I made two edits in https://github.com/gslab-econ/gslab_latex/commit/9bfb994283d8682f85c06199a8b05f8d65789d5e#diff-04c6e90faac2675aa89e2176d2eec7d8. If you agree, feel free to merge and close.

**Comment by arosenbe** [comment]
Good stuff. Thanks @lboxell!

**Comment by arosenbe** [comment]
Summary comment, 

This issue updates the [readme](https://github.com/gslab-econ/gslab_latex/blob/ee6960c54c9f74f1b48be0341d79b73c97f055f2/README.md) to comply with the [licensing information from the original metropolis beamer theme](https://github.com/gslab-econ/gslab_latex/blob/20b0482bcc8c38821c0565b096ae7aed6f3d7b5c/beamertheme_metropolis/orig/mtheme-master/README.md).
