### ISSUE TITLE
Improve instructions to install gslab_metropolis on Windows

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/gslab_latex#3]
Follow up on unresolved problem on template/#8 and in support of template/#20, this task seeks to make it easier to install gslab_metropolis theme given a MiKTeX installation.

**Comment by stanfordquan** [comment]
@yuchuan2016 ,

Would you like to try the above commit to see if you can install the theme on Windows?

The procedure is:

- Pull the above commit (c08d722)

- Open MiKTeX Settings (Admin), navigate to Roots, click Add, and then add gslab_latex to the Roots path.

- Go to General, click Refresh FNDB and Update Formats. 

- Reconfigure LyX. Then go to TeX Information, make sure in LaTeX styles, `beamerthememetropolis_gslab.sty` is there. 

- Compile and see what happens!

I'm facing issues with my LyX installation on Windows machine, but beside that I think this method should work.

**Comment by yuchuan2016** [comment]
@stanfordquan ,

Fantastic! It works! One issue is that when I click Update Formats, it warns:

<img width="499" src="https://cloud.githubusercontent.com/assets/16677008/22170054/3dc7aadc-df2e-11e6-86e7-1de876114907.jpeg">

But the slide is compiled successfully.

**Comment by lboxell** [comment]
@stanfordquan,

Flagging this as stale.

**Comment by stanfordquan** [comment]
Working on it now over at mtheme.

**Comment by stanfordquan** [comment]
Gonna go through the above instructions today on a fresh Windows VM. If it works as intended I think we can close this task and chalk the failure of one PI's to install it earlier this year as user-error

**Comment by stanfordquan** [comment]
Haven't had the chance re-install on Windows. Will do after production.

**Comment by stanfordquan** [comment]
Pull request over at `gslab_mtheme`.
