### ISSUE TITLE
Update gslab_latex repo

### ISSUE THREAD

**Issue by lboxell** [gslab-econ/gslab_latex#4]
- Update gslab-latex repo to be a proper fork of original metropolis repo (maybe rename to be just metropolis theme rather than general latex)
  - Eliminate redundant readmes in gslab_latex repo
  - Ensure license is appropriate

**Comment by lboxell** [comment]
See https://github.com/gslab-econ/mtheme

**Comment by lboxell** [comment]
@stanfordquan,

Can you PR this?  Since it is relevant to #5. New repo is at https://github.com/gslab-econ/mtheme and the master branch should be good.

**Comment by lboxell** [comment]
@stanfordquan,

See previous comment (added you as an assignee so you can track this, since there is no pull request).

**Comment by stanfordquan** [comment]
Will get on this

**Comment by stanfordquan** [comment]
Everything looks good in the fork. I think the next step is wiping the gslab_latex repo but for a redirection to the forked mtheme repo, and collapse the `readme.md` to contain only information relevant to our users.

**Comment by stanfordquan** [comment]
I did the above [here](https://github.com/gslab-econ/mtheme/tree/issue4_cleanup).

**Comment by lboxell** [comment]
Created PR in https://github.com/gslab-econ/gslab_latex/pull/6 and https://github.com/gslab-econ/mtheme/pull/2.

**Comment by lboxell** [comment]
Closing task.

Summary: 
 - Created fork of metropolis theme: https://github.com/gslab-econ/mtheme
 - Deleted gslab_latex except for pointer.
